import Icon from "./PixelIcon";

export const PSYSTREAM_URL = "https://stream.psymariux.dev";

export function PsyStreamDetails() {
  return <div className="psystream-details"><img className="psystream-wordmark" src="/art/psystream-wordmark.svg" width={222} height={48} alt="PsyStream" /><p>I build and maintain PsyStream, a streaming site for movies, series, anime and live sport. It has watchlists, watch history, offline features and group viewing.</p><img className="psystream-detail-preview" src="/art/psystream-preview.webp" width={1200} height={675} alt="A captured view of PsyStream’s public homepage, with its navigation and featured anime." loading="lazy" /><div className="psystream-tags"><span>Live project</span><span>Closed source</span></div><p className="source-note">The source code is private.</p><a className="pixel-button" href={PSYSTREAM_URL} target="_blank" rel="noopener noreferrer">Visit PsyStream<Icon name="external-link" /></a></div>;
}

export default function PsyStream({ onDetails }: { onDetails: () => void }) {
  return <section className="psystream-section" id="psystream" aria-labelledby="psystream-heading"><div className="psystream-copy"><div className="psystream-tags"><span>Featured project</span><span>Closed source</span></div><h2 id="psystream-heading">PsyStream</h2><p>My streaming project for movies, series, anime and live sport. Save a watchlist and resume from your watch history.</p><div className="psystream-actions"><a className="pixel-button" href={PSYSTREAM_URL} target="_blank" rel="noopener noreferrer">Visit PsyStream<Icon name="external-link" /></a><button className="text-button" onClick={onDetails} aria-haspopup="dialog">About the project</button></div><span className="psystream-address">stream.psymariux.dev</span></div><figure className="psystream-frame"><div className="psystream-screen-bar"><img src="/art/psystream-wordmark.svg" alt="" width={148} height={32} loading="lazy" /><span>Live project</span></div><a href={PSYSTREAM_URL} target="_blank" rel="noopener noreferrer" aria-label="Explore PsyStream’s live website, opens in a new tab"><img src="/art/psystream-preview.webp" width={1200} height={675} loading="lazy" alt="PsyStream’s public homepage: a cinematic anime feature and navigation for movies, series, anime and sport." /></a><figcaption>PsyStream’s public homepage.</figcaption></figure></section>;
}
