import Icon from "./PixelIcon";

export const PSYSTREAM_URL = "https://stream.psymariux.dev";

export function PsyStreamDetails() {
  return <div className="psystream-details"><img className="psystream-wordmark" src="/art/psystream-wordmark.svg" width={222} height={48} alt="PsyStream" /><p>My personal streaming project, already on the web. Movies, series, anime and live sport, with a watchlist, watch history, offline features and group viewing.</p><img className="psystream-detail-preview" src="/art/psystream-preview.webp" width={1200} height={675} alt="A captured view of PsyStream’s public homepage, with its navigation and featured anime." loading="lazy" /><div className="psystream-tags"><span>Live project</span><span>Closed source</span></div><p className="source-note">Built and maintained by Psymariux. The source code is private, so this project has no public repository chest. Features and branding are taken from its public site.</p><a className="pixel-button" href={PSYSTREAM_URL} target="_blank" rel="noopener noreferrer">Visit PsyStream<Icon name="external-link" /></a></div>;
}

export default function PsyStream({ onDetails }: { onDetails: () => void }) {
  return <section className="psystream-section" id="psystream" aria-labelledby="psystream-heading"><div className="psystream-copy"><div className="psystream-tags"><span>Featured project</span><span>Closed source</span></div><h2 id="psystream-heading">PsyStream.<br />A screen of my own.</h2><p>Movies, series, anime and live sport. A personal project I build and maintain, with watchlists, watch history and a place to pick up where you left off.</p><div className="psystream-actions"><a className="pixel-button" href={PSYSTREAM_URL} target="_blank" rel="noopener noreferrer">Visit PsyStream<Icon name="external-link" /></a><button className="text-button" onClick={onDetails} aria-haspopup="dialog">About the project</button></div><span className="psystream-address">stream.psymariux.dev</span></div><figure className="psystream-frame"><div className="psystream-screen-bar"><img src="/art/psystream-wordmark.svg" alt="" width={148} height={32} loading="lazy" /><span>Live project</span></div><a href={PSYSTREAM_URL} target="_blank" rel="noopener noreferrer" aria-label="Explore PsyStream’s live website, opens in a new tab"><img src="/art/psystream-preview.webp" width={1200} height={675} loading="lazy" alt="PsyStream’s public homepage: a cinematic anime feature and navigation for movies, series, anime and sport." /></a><figcaption>A look at the live product. The matching painting is hanging in the workshop.</figcaption></figure></section>;
}
